version: "3.8"
services:
    server1:
        image: serverapp:latest
        networks:
            - servers
        ports:
            - 3001:3000
        environment:
            LB_TYPE: roundrobin
    server2:
        image: serverapp:latest
        networks:
            - servers
        environment:
            LB_TYPE: roundrobin
    server3:
        image: serverapp:latest
        networks:
            - servers
        environment:
            LB_TYPE: roundrobin
    server4:
        image: serverapp:latest
        networks:
            - leastconn
        environment:
            LB_TYPE: leastconn
            PORT: 80
    server5:
        image: serverapp:latest
        networks:
            - leastconn
        environment:
            LB_TYPE: leastconn
            PORT: 80
    server6:
        image: serverapp:latest
        networks:
            - leastconn
        environment:
            LB_TYPE: leastconn
            PORT: 80
    loadbalancer:
        build:
            context: nginx-image
        ports: 
            - 3000:80
        restart: always
        deploy:
            replicas: 1
            labels: [APP=BALANCER]
        depends_on:
            - server1
            - server2
            - server3
            - server4
            - server5
            - server6
        networks:
            - servers
            - leastconn
networks:
    servers:
    leastconn:

volumes:
    shared:
